---
title: "R Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tokenizers")
#install.packages('arules')
#install.packages('tidyverse')
#install.packages('knitr')
```


```{r}
#Note: The following code is specific from user to user

library(arules)
library(tidyverse)
library(arules)
library(stringr)
#install.packages('arulesViz')
library(arulesViz)

setwd("C:\\Users\\wyett\\OneDrive\\Documents\\INFO5871\\Assignment1\\") #to set the new working Directory
data <- read.csv('resourceFiles\\basketData.csv', header = FALSE, sep = ',')

#head(data)

```
```{r}
transtotal <- arules::read.transactions("C:\\Users\\wyett\\OneDrive\\Documents\\INFO5871\\Assignment1\\resourceFiles\\basketData.csv",
                  rm.duplicates = TRUE, 
                  format = "basket",  ##if you use "single" also use cols=c(1,2)
                  sep=",",  ## csv file
                  cols=NULL) ## The dataset has no row numbers

print(typeof(transtotal))

```

```{r}

rules = arules::apriori(transtotal, parameter = list(support = 0.3,confidence = 0.6), maxlen=5)
print(length(rules))
rules <- subset(rules, subset = arules::size(arules::lhs(rules)) != 0)
#print(arules::inspect(rules))
top.conf <- sort(rules, decreasing = TRUE, na.last = NA, by = "lift")
inspect(head(top.conf, 10))
```

```{r}
plot(rules, method="graph")

```

Left and right side control:
```{r}
rules = arules::apriori(transtotal, parameter = list(support = 0.3,confidence = 0.6), maxlen=5,appearance = list(lhs = c("state"), default="rhs"))
print(length(rules))
rules <- subset(rules, subset = arules::size(arules::lhs(rules)) != 0)
print(arules::inspect(rules))

```

```{r}
rules = arules::apriori(transtotal, parameter = list(support = 0.3,confidence = 0.6), maxlen=5,appearance = list(rhs = c("energy"), default="lhs"))
print(length(rules))
rules <- subset(rules, subset = arules::size(arules::lhs(rules)) != 0)
#print(arules::inspect(rules))

top.support <- sort(rules, decreasing = TRUE, na.last = NA, by = "support")
inspect(head(top.support, 10))
```

```{r}
plot(rules, method="graph")
```



```{r}
## Hierarchical clustering 

# ----
library(dplyr)       # for data manipulation
library(ggplot2)     # for data visualization

# ---
#install.packages("cluster")
library(cluster)     # for general clustering algorithms
#install.packages('factoextra')
library(factoextra)  # for visualizing cluster results

## !!!!!!!!!!!!!!!!!
## You CANNOT use distance metrics on non-numeric data
## Before we can proceed - we need to REMOVE
## all non-numeric columns
setwd("C:\\Users\\wyett\\OneDrive\\Documents\\INFO5871\\Assignment1\\") #to set the new working Directory
print(getwd())
filepath <- 'resourceFiles\\tfidfData.csv'
textData <- read.csv(filepath)
textVectors <- textData[,c(-1,-2,-3)]
```
```{r}

# Dissimilarity matrix with Euclidean
## dist in R
##  "euclidean", "maximum", "manhattan", 
## "canberra", "binary" or "minkowski" with p
(dE <- dist(textVectors, method = "euclidean"))
(dM <- dist(textVectors, method = "manhattan"))
(dMp2 <- dist(textVectors, method = "minkowski", p=2))

# Hierarchical clustering using Complete Linkage
(hc_C <- hclust(dM, method = "complete" ))
plot(hc_C)
hc_D <- hclust(dE, method = "ward.D" )
plot(hc_D)
hc_D2 <- hclust(dMp2, method = "ward.D2" )
plot(hc_D2)
```

```{r}

#(My_m <- (as.matrix(scale(t(SmallCorpus_DF_DT)))))
My_m = as.matrix(textVectors)
print(textVectors)
(My_cosine_dist = 1-crossprod(My_m) /(sqrt(colSums(My_m^2)%*%t(colSums(My_m^2)))))
# create dist object
My_cosine_dist <- as.dist(My_cosine_dist) ## Important
HClust_Ward_CosSim_SmallCorp2 <- hclust(My_cosine_dist, method="ward.D")
plot(HClust_Ward_CosSim_SmallCorp2, cex=.7, hang=-30,main = "Cosine Sim")
rect.hclust(HClust_Ward_CosSim_SmallCorp2, k=5)


######## Have a look ..........................
#plot(hc_D2)
#plot(hc_D)
#plot(hc_C)
#plot(hc_CS)


```